### ISSUE TITLE
Master issue

### ISSUE THREAD

**Issue by ddenisenko** [ddenisenko/test#3]
High-level issue pointing to low-level ones.

We need to do the following:
- [x] #1 
- [ ] #2 
- [ ] https://github.com/ddenisenko/test/issues/1
- [ ] https://github.com/mulesoft/api-workbench/issues/13
- [ ] https://github.com/mulesoft/api-workbench/issues/60

**Comment by ddenisenko** [comment]
needs #2 , #1

**Comment by ddenisenko** [comment]
needs #1
